# Generated by Django 2.1.2 on 2018-10-20 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_credits', models.IntegerField()),
                ('course_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_email', models.EmailField(max_length=20)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.Partner', to_field='referral_code')),
            ],
        ),
    ]
