# Generated by Django 2.1.2 on 2018-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='referral_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
