# Generated by Django 2.1.2 on 2018-10-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20181021_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='referral_code',
            field=models.CharField(default=None, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='referral_credits',
            field=models.IntegerField(default=5),
        ),
    ]
