# Generated by Django 2.1.2 on 2018-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20181021_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='course_credits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='referral_credits',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
